name: Build Annas Browser
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Build with Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./src-tauri
          distPath: ./dist
          args: --bundles msi

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: Annas-Browser-exe
          path: src-tauri/target/release/*.exe

      - name: Upload msi
        uses: actions/upload-artifact@v4
        with:
          name: Annas-Browser-msi
          path: src-tauri/target/release/bundle/msi/*.msi
